export const GLOSSARY = {
  "revenue": { def: "The total money a company took in from selling its products or services, before any costs are subtracted.", analogy: "Like a lemonade stand's total cash from cups sold, before paying for lemons or cups." },
  "net income": { def: "What's left of revenue after every single cost, tax and expense is subtracted — the 'bottom line' profit.", analogy: "The allowance you actually get to keep after chores, minus what you spent on supplies." },
  "operating margin": { def: "Operating income divided by revenue — how much profit the core business keeps from each dollar of sales, before interest and taxes.", analogy: "If a $10 sale leaves $2 of operating profit, the operating margin is 20%." },
  "net margin": { def: "Net income divided by revenue — how many cents of pure profit are left from every dollar sold.", analogy: "A 15% net margin means 15 cents of every $1 in sales become actual profit." },
  "roe": { def: "Return on Equity: net income divided by shareholders' equity — how efficiently a company turns owners' money into profit.", analogy: "If you put $100 into a business and it earns you $15 a year, that's a 15% ROE." },
  "roa": { def: "Return on Assets: net income divided by total assets — how efficiently a company turns everything it owns into profit.", analogy: "A factory that earns more per dollar of equipment is more efficient, not just bigger." },
  "debt-to-equity": { def: "Long-term debt divided by shareholders' equity — how much a company relies on borrowed money versus owners' money.", analogy: "Buying a $300,000 house with a $250,000 mortgage is high leverage; paying mostly cash is low leverage." },
  "free cash flow": { def: "Cash generated by operations minus the money spent maintaining and growing the business (capital expenditures) — cash truly left over.", analogy: "Your paycheck minus rent, bills and required home repairs — what's actually free to save or spend." },
  "owner earnings": { def: "A Buffett-popularized approximation of free cash flow available to shareholders, used to estimate what a business is really worth to its owner.", analogy: "Think of it as the 'true profit' a private owner could pocket every year." },
  "book value": { def: "Shareholders' equity — what would theoretically be left for owners if the company sold everything and paid off every debt.", analogy: "Like your net worth: everything you own minus everything you owe." },
  "intrinsic value": { def: "An estimate of what a business is really worth based on the cash it can generate, independent of its current stock price.", analogy: "The price a knowledgeable private buyer might actually pay for the whole business." },
  "margin of safety": { def: "How far a stock's price sits below an estimate of intrinsic value — a cushion against being wrong.", analogy: "Buying a used car you value at $10,000 for $7,000 gives you room for surprise repairs." },
  "p/e ratio": { def: "Price-to-Earnings: the stock price divided by earnings per share — how many years of current profit you're paying for.", analogy: "A P/E of 15 means you're paying 15x this year's per-share profit for one share." },
  "p/b ratio": { def: "Price-to-Book: the stock price divided by book value per share — how the market values the company versus its accounting net worth.", analogy: "A P/B under 1 means the stock trades for less than its own accounting net worth." },
  "eps": { def: "Earnings Per Share: net income divided by the number of shares outstanding — profit sliced into one-share-sized pieces.", analogy: "If a pizza (profit) is cut into 8 slices (shares), EPS is the size of one slice." },
  "diluted shares": { def: "The share count including stock options, convertible bonds and other securities that could turn into shares — the most conservative share count.", analogy: "Counting everyone who could show up to dinner, not just those who already RSVP'd." },
  "dilution": { def: "An increase in shares outstanding that shrinks each existing shareholder's slice of the company.", analogy: "Cutting the same pizza into more slices — each slice gets smaller even though the pizza didn't." },
  "cagr": { def: "Compound Annual Growth Rate: the steady yearly growth rate that would take a starting value to an ending value over a given number of years.", analogy: "The 'average speed' of growth, smoothed over the whole trip rather than any single leg." },
  "red flag": { def: "A pattern in the filed numbers — like debt rising for years, or profit not turning into cash — that historically has warranted closer scrutiny.", analogy: "A warning light on a car dashboard: not proof of a breakdown, but worth checking." },
  "10-k": { def: "A company's detailed annual report filed with the SEC, audited and far more thorough than a press release.", analogy: "The company's full, notarized diary entry for the year, not just the highlight reel." },
  "xbrl": { def: "A structured, machine-readable data format the SEC requires companies to file alongside their reports, tagging every number so software can read it directly.", analogy: "Instead of a PDF you have to read by eye, it's a spreadsheet a computer can read directly." },
  "fiscal year": { def: "A company's own 12-month accounting year, which doesn't always match the calendar year.", analogy: "Some schools run September to June; some companies run February to January." },
  "stockholders' equity": { def: "Total assets minus total liabilities — the accounting value belonging to shareholders.", analogy: "Your house's value minus what you still owe the bank is your equity in it." },
  "capital expenditures": { def: "Money spent buying, building or maintaining long-term assets like factories, equipment or stores.", analogy: "The cost of a new roof or a new delivery van, not the electric bill." },
  "cash conversion": { def: "How closely free cash flow tracks reported net income — a check on whether 'profit' is really turning into spendable cash.", analogy: "A friend who says they're 'rich' but has no cash on hand has a cash-conversion problem." },
  "leverage": { def: "The use of borrowed money to fund a business — higher leverage means higher risk and higher potential reward.", analogy: "A small down payment on a house is high leverage; paying in full is no leverage at all." },
};

let tooltipEl = null;

export function initGlossary() {
  tooltipEl = document.getElementById("glossary-tooltip");
  document.addEventListener("mouseover", handleHover);
  document.addEventListener("mouseout", handleOut);
  document.addEventListener("click", handleTapMobile);
}

function lookup(key) {
  return GLOSSARY[key.toLowerCase()];
}

function showTooltip(target, entry) {
  tooltipEl.innerHTML = `<div class="g-term">${target.textContent}</div><div>${entry.def}</div><div class="g-analogy">${entry.analogy}</div>`;
  const rect = target.getBoundingClientRect();
  tooltipEl.classList.remove("hidden");
  const top = rect.bottom + 8;
  let left = rect.left;
  const maxLeft = window.innerWidth - 300;
  if (left > maxLeft) left = maxLeft;
  tooltipEl.style.top = `${top}px`;
  tooltipEl.style.left = `${Math.max(8, left)}px`;
}

function hideTooltip() {
  tooltipEl?.classList.add("hidden");
}

function handleHover(e) {
  const target = e.target.closest(".term");
  if (!target) return;
  const entry = lookup(target.dataset.term || target.textContent);
  if (entry) showTooltip(target, entry);
}

function handleOut(e) {
  const target = e.target.closest(".term");
  if (target) hideTooltip();
}

function handleTapMobile(e) {
  const target = e.target.closest(".term");
  if (!target) {
    if (!e.target.closest("#glossary-tooltip")) hideTooltip();
    return;
  }
  const entry = lookup(target.dataset.term || target.textContent);
  if (entry) {
    e.preventDefault();
    showTooltip(target, entry);
  }
}

// Wraps a plain-text label in a hoverable/tappable glossary span if a
// definition exists for it; otherwise returns the label unchanged.
export function term(label, key) {
  const lookupKey = (key || label).toLowerCase();
  if (!GLOSSARY[lookupKey]) return label;
  return `<span class="term" data-term="${lookupKey}">${label}</span>`;
}
